---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: fetch-data
spec:
  description: This task uses wget to download files from the internet to a workspace.
  params:
    - default: ""
      description: The url we want to download file from
      name: url
      type: string
    - default: []
      description: The directory path we want to save file to
      name: diroptions
      type: array
    - default: []
      description: The arguments to pass to wget
      name: options
      type: array
    - default: ""
      description: The filename we want to change our file to
      name: filename
      type: string
    - default: quay.io/khrm/wget:latest
      description: The wget docker image to be used
      name: wget-option
      type: string
  steps:
    - args:
        - $(params.options[*])
        - $(params.url)
        - $(params.diroptions[*])
      command:
        - wget
      image: quay.io/khrm/wget:latest
      name: fetch-data
  workspaces:
    - description: The folder where we write the wget'ed file to
      name: data
