apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: "demo-pipeline"
spec:
  params:
    - name: filename
      type: string
      description: The name of the file to be created
    - name: url
      type: string
  workspaces:
    - name: shared-workspace
  tasks:
    - name: fetch-data
      taskRef:
        name: wget
      workspaces:
        - name: wget-workspace
          workspace: shared-workspace
      params:
        - name: options
          value:
            - "-O"
            - $(workspaces.wget-workspace.path)/$(params.filename)
        - name: url
          value: "$(params.url)"
