apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: "unicredit-demo-pipeline"
spec:
  params:
    - name: path
      type: string
      description: The path of the file to be created
  workspaces:
    - name: shared-workspace
  tasks:
    - name: write-file
      taskRef:
        name: write-file
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: path
          value: "$(params.path)"
        - name: contents
          value: |
            "hello"
            "hi"
    - name: check-file
      params:
        - name: path
          value: "$(params.path)"
      workspaces:
        - name: source
          workspace: shared-workspace
      runAfter:
        - write-file
      taskSpec:
        params:
          - name: path
        workspaces:
          - name: source
            description: The workspace to check for the file
        results:
          - name: exists
            description: indicates whether the file exists or is missing
        steps:
          - name: check-file
            image: alpine
            script: |
              if test -f $(workspaces.source.path)/$(params.path); then
                printf yes | tee $(results.exists.path)
              else
                printf no | tee $(results.exists.path)
              fi
