apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: "unicredit-demo-pipeline"
spec:
  params:
    - name: path
      type: string
      description: The path of the file to be created
  workspaces:
    - name: shared-workspace
  tasks:
    - name: write-file
      taskRef:
        name: write-file
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: path
          value: "$(params.path)"
        - name: contents
          value: |
            "hello"
            "hi"
